version: '3.4'

volumes:
  redis:

services:
  redis:
    image: redis:5
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  ex:
    build:
      context: ex_message_bus/
      dockerfile: Dockerfile
    command: "tail -f /dev/null"
    links:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./ex_message_bus:/mnt/code

  rails:
    build:
      context: mini-sledge
      dockerfile: Dockerfile
    links:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./mini-sledge:/mnt/code
    ports:
      - "3000:3000"

  ruby-processor:
    build:
      context: mini-sledge
      dockerfile: Dockerfile
    command: "rake sledge_listener:start"
    links:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./mini-sledge:/mnt/code
